language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm test
- npm run build
deploy:
  deploy:
  provider: heroku
  app: cicd-reactjs-training
  api_key:
    secure: WyznvAu3u44UFA2gv012TR7e9FOyhHz4le0aAalpWuzTzVzT0uRLnn7KzTYW0G+WvYVv227aEzMjH7f6tvhUKnWgEQl1X+9LMYUjxgNwyd9u7PUGc4Q7hvnKyHa8X4+gxdVZtTehmRJyAPX2/4I1rIiIv87P9cuu1i0QGg5XnCSVRyGiDpYf4Toi5BSUTHHJt/Di5Z69n/7Y0GTxFe0BS42OwWEYJepZyNKgGe7ao6mGWwZH9Zy27tlwoHwkbWpRrRVRz48Gva0g7wFEXHzy6V8K9CqGHthX7oNCT4ewkaIsClbu3TGxmK/+SL7mR73/pfNydffIm1fw3uBsqBj7acjEVTFnLfQP30GeDwRCkX+v8Z6TDjmDYwcho06M8hiWO4IoqtNw5atl2D68EDYC3gZFzPdfTxZj2U5W+AeW6UjdLp2PVhjagemlXDtU/sHlWpkihJcSzZgGgdhzoLop68DjFV14fl70xTVPWGPItpDeWlleZd9TcxrC7fD4P7YEBtRWR1yOUej/tlShgjPTzJRux/P5EJggX2NdiCAnjR2bXFs6CsEFs7ql/F7Jt8lTGUGUBIM2owi5nd5jvvrZwsuMVMYiO5J0ZExu/E70hkGh8mZhEnOIPCcXEFY6+90OBOG/B4UOAN4bCuOkkbbW/V94kFuwcgQv+a523rR3dEE=
